from collections.abc import Generator

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import get_settings


settings = get_settings()
connect_args = {"check_same_thread": False} if settings.database_url.startswith("sqlite") else {}
engine = create_engine(settings.database_url, connect_args=connect_args)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    pass


def get_db() -> Generator[Session, None, None]:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db() -> None:
    from app.db import models  # noqa: F401

    Base.metadata.create_all(bind=engine)
    ensure_schema_for_engine(engine)


def ensure_schema() -> None:
    ensure_schema_for_engine(engine)


def ensure_schema_for_engine(target_engine) -> None:
    additions = {
        "customers": {
            "delegation": "VARCHAR(120)",
            "assigned_salesperson": "VARCHAR(180)",
            "accounting_code": "VARCHAR(100)",
            "company_inactive": "BOOLEAN DEFAULT 0",
            "category": "VARCHAR(120)",
            "deleted_at": "DATETIME",
            "deleted_by": "INTEGER",
        },
        "companies": {
            "legal_name": "VARCHAR(255)",
            "active": "BOOLEAN DEFAULT 1",
            "plan": "VARCHAR(80)",
            "tax_id": "VARCHAR(80)",
            "email": "VARCHAR(255)",
            "phone": "VARCHAR(80)",
            "web": "VARCHAR(255)",
            "address": "VARCHAR(500)",
            "country": "VARCHAR(120)",
            "currency": "VARCHAR(10) DEFAULT 'EUR'",
            "notification_email": "VARCHAR(255)",
            "responsible_contact": "VARCHAR(255)",
            "default_language": "VARCHAR(20) DEFAULT 'es'",
            "updated_at": "DATETIME",
        },
        "products": {
            "brand": "VARCHAR(150)",
            "usual_supplier": "VARCHAR(255)",
            "sale_price": "FLOAT",
            "discount_percent": "FLOAT",
            "size_group": "VARCHAR(120)",
            "colors": "VARCHAR(255)",
            "entry_date": "VARCHAR(50)",
            "obsolete": "BOOLEAN DEFAULT 0",
            "article_type": "VARCHAR(120)",
            "description_cont": "TEXT",
            "warehouse_location_code": "VARCHAR(120)",
            "replenishment_warehouse": "VARCHAR(120)",
            "deleted_at": "DATETIME",
            "deleted_by": "INTEGER",
        },
        "orders": {
            "deleted_at": "DATETIME",
            "deleted_by": "INTEGER",
            "delete_reason": "TEXT",
        },
        "decision_settings": {
            "enable_exact_match": "BOOLEAN DEFAULT 1",
            "enable_alias_match": "BOOLEAN DEFAULT 1",
            "enable_relation_match": "BOOLEAN DEFAULT 1",
            "enable_history_match": "BOOLEAN DEFAULT 1",
            "enable_rag_match": "BOOLEAN DEFAULT 1",
            "enable_llm_support": "BOOLEAN DEFAULT 1",
            "exact_priority": "INTEGER DEFAULT 1",
            "alias_priority": "INTEGER DEFAULT 2",
            "relation_priority": "INTEGER DEFAULT 3",
            "history_priority": "INTEGER DEFAULT 4",
            "rag_priority": "INTEGER DEFAULT 5",
            "llm_priority": "INTEGER DEFAULT 6",
            "customer_weight": "INTEGER DEFAULT 20",
            "product_weight": "INTEGER DEFAULT 35",
            "quantities_weight": "INTEGER DEFAULT 15",
            "history_weight": "INTEGER DEFAULT 10",
            "coherence_weight": "INTEGER DEFAULT 10",
            "rag_weight": "INTEGER DEFAULT 5",
            "llm_weight": "INTEGER DEFAULT 5",
            "min_alias_confidence": "FLOAT DEFAULT 0.85",
            "min_history_frequency": "INTEGER DEFAULT 3",
            "min_product_frequency": "INTEGER DEFAULT 2",
            "max_doubtful_lines": "INTEGER DEFAULT 1",
            "learning_mode": "VARCHAR(50) DEFAULT 'supervisado'",
            "always_human_review": "BOOLEAN DEFAULT 1",
            "auto_approve_aliases": "BOOLEAN DEFAULT 0",
            "block_new_customer": "BOOLEAN DEFAULT 0",
            "block_conflicting_aliases": "BOOLEAN DEFAULT 1",
            "block_missing_quantity": "BOOLEAN DEFAULT 1",
            "block_missing_reference": "BOOLEAN DEFAULT 1",
            "updated_at": "DATETIME",
        },
        "email_settings": {
            "imap_host": "VARCHAR(255)",
            "imap_port": "INTEGER DEFAULT 993",
            "imap_use_ssl": "BOOLEAN DEFAULT 1",
            "imap_security": "VARCHAR(30) DEFAULT 'ssl_tls'",
            "imap_username": "VARCHAR(255)",
            "imap_password_encrypted": "TEXT",
            "test_read_limit": "INTEGER DEFAULT 10",
            "oauth_scopes": "TEXT",
            "mailbox": "VARCHAR(255)",
            "error_folder": "VARCHAR(100)",
            "no_order_folder": "VARCHAR(100)",
            "doubtful_folder": "VARCHAR(100)",
            "read_limit": "INTEGER DEFAULT 25",
            "auto_sync_enabled": "BOOLEAN DEFAULT 0",
            "read_unread_only": "BOOLEAN DEFAULT 1",
            "read_from_date": "VARCHAR(50)",
            "mark_as_read_after_import": "BOOLEAN DEFAULT 0",
            "move_after_processing": "BOOLEAN DEFAULT 0",
            "smtp_provider": "VARCHAR(50) DEFAULT 'smtp'",
            "smtp_host": "VARCHAR(255)",
            "smtp_port": "INTEGER DEFAULT 587",
            "smtp_security": "VARCHAR(30) DEFAULT 'starttls'",
            "smtp_username": "VARCHAR(255)",
            "smtp_password_encrypted": "TEXT",
            "from_email": "VARCHAR(255)",
            "from_name": "VARCHAR(255)",
            "reply_to": "VARCHAR(255)",
            "default_cc": "TEXT",
            "default_bcc": "TEXT",
            "save_internal_copy": "BOOLEAN DEFAULT 1",
            "preserve_thread_headers": "BOOLEAN DEFAULT 1",
            "auto_process_on_fetch": "BOOLEAN DEFAULT 0",
            "process_only_with_attachments": "BOOLEAN DEFAULT 0",
            "process_only_with_pdf": "BOOLEAN DEFAULT 0",
            "process_without_attachments": "BOOLEAN DEFAULT 1",
            "process_read_emails": "BOOLEAN DEFAULT 0",
            "avoid_duplicates_by_message_id": "BOOLEAN DEFAULT 1",
            "allow_reprocess": "BOOLEAN DEFAULT 0",
            "auto_create_order_if_detected": "BOOLEAN DEFAULT 1",
            "always_human_review": "BOOLEAN DEFAULT 1",
            "mark_doubtful_below_threshold": "BOOLEAN DEFAULT 1",
            "mark_no_order_if_detected": "BOOLEAN DEFAULT 1",
            "action_order_detected": "VARCHAR(80) DEFAULT 'move_processed'",
            "action_no_order": "VARCHAR(80) DEFAULT 'move_no_order'",
            "action_doubtful": "VARCHAR(80) DEFAULT 'move_doubtful'",
            "action_error": "VARCHAR(80) DEFAULT 'move_error'",
            "minimum_score_auto_order": "INTEGER DEFAULT 90",
            "visible_states": "TEXT DEFAULT 'pending,processing,pedido,no_pedido,dudoso,error_processing,pending_reprocess,responded,closed'",
            "default_filter": "VARCHAR(80) DEFAULT 'all'",
            "default_date_range": "VARCHAR(80) DEFAULT 'today'",
            "default_page_size": "INTEGER DEFAULT 25",
            "default_sort": "VARCHAR(80) DEFAULT 'date_desc'",
            "show_summary_cards": "BOOLEAN DEFAULT 1",
            "show_score_column": "BOOLEAN DEFAULT 1",
            "show_customer_column": "BOOLEAN DEFAULT 1",
            "show_attachments_column": "BOOLEAN DEFAULT 1",
            "show_order_column": "BOOLEAN DEFAULT 1",
            "show_reply_button": "BOOLEAN DEFAULT 1",
            "show_process_button": "BOOLEAN DEFAULT 1",
            "signature_text": "TEXT DEFAULT 'Equipo de pedidos'",
            "signature_html": "TEXT",
            "use_signature": "BOOLEAN DEFAULT 1",
            "include_logo_in_signature": "BOOLEAN DEFAULT 0",
            "legal_footer": "TEXT",
            "last_imap_test_at": "DATETIME",
            "last_imap_test_ok": "BOOLEAN",
            "last_imap_test_message": "TEXT",
            "last_sync_at": "DATETIME",
            "last_sync_ok": "BOOLEAN",
            "last_sync_message": "TEXT",
            "last_sync_error": "TEXT",
            "last_sync_new": "INTEGER DEFAULT 0",
            "last_sync_duplicates": "INTEGER DEFAULT 0",
            "last_smtp_test_at": "DATETIME",
            "last_smtp_test_ok": "BOOLEAN",
            "last_smtp_test_message": "TEXT",
            "updated_by": "INTEGER",
            "created_at": "DATETIME",
            "updated_at": "DATETIME",
        },
        "emails": {
            "agent_status": "VARCHAR(80) DEFAULT 'not_processed'",
            "has_attachments": "BOOLEAN DEFAULT 0",
            "has_pdf": "BOOLEAN DEFAULT 0",
            "processing_error": "TEXT",
            "processing_result_json": "TEXT",
            "last_processed_at": "DATETIME",
        },
        "email_attachments": {
            "size_bytes": "INTEGER DEFAULT 0",
            "is_pdf": "BOOLEAN DEFAULT 0",
            "extraction_status": "VARCHAR(80) DEFAULT 'pending'",
            "extraction_error": "TEXT",
        },
        "llm_settings": {
            "agent_enabled": "BOOLEAN DEFAULT 1",
            "agent_mode": "VARCHAR(80) DEFAULT 'semiautomatico'",
            "safety_level": "VARCHAR(50) DEFAULT 'equilibrado'",
            "use_same_model_for_all": "BOOLEAN DEFAULT 1",
            "can_read_email": "BOOLEAN DEFAULT 1",
            "can_extract_pdf": "BOOLEAN DEFAULT 1",
            "can_classify_email": "BOOLEAN DEFAULT 1",
            "can_extract_order": "BOOLEAN DEFAULT 1",
            "can_suggest_customer": "BOOLEAN DEFAULT 1",
            "can_suggest_products": "BOOLEAN DEFAULT 1",
            "can_calculate_score": "BOOLEAN DEFAULT 1",
            "can_create_pending_order": "BOOLEAN DEFAULT 1",
            "can_mark_no_order": "BOOLEAN DEFAULT 1",
            "can_reply_customer": "BOOLEAN DEFAULT 0",
            "allow_auto_confirm": "BOOLEAN DEFAULT 0",
            "allow_auto_export": "BOOLEAN DEFAULT 0",
            "daily_cost_limit": "FLOAT DEFAULT 0",
            "batch_limit": "INTEGER DEFAULT 25",
            "detailed_llm_logs": "BOOLEAN DEFAULT 0",
            "store_llm_payloads": "BOOLEAN DEFAULT 0",
            "anonymize_llm_logs": "BOOLEAN DEFAULT 1",
            "debug_mode": "BOOLEAN DEFAULT 0",
            "organization_id": "VARCHAR(255)",
            "project_id": "VARCHAR(255)",
            "azure_deployment_name": "VARCHAR(255)",
            "last_test_at": "DATETIME",
            "last_test_ok": "BOOLEAN",
            "last_test_message": "TEXT",
            "last_error": "TEXT",
            "last_response_ms": "INTEGER",
            "updated_by": "INTEGER",
            "created_at": "DATETIME",
            "updated_at": "DATETIME",
        },
        "imports": {
            "rows_ignored": "INTEGER DEFAULT 0",
            "mapping_used": "TEXT",
            "user_id": "INTEGER",
        },
        "prompt_versions": {
            "created_by_user_id": "INTEGER",
        },
        "branding_settings": {
            "dark_logo_url": "VARCHAR(500)",
            "favicon_url": "VARCHAR(500)",
            "updated_by": "INTEGER",
        },
        "input_channels": {
            "channel_type": "VARCHAR(50) DEFAULT 'message'",
            "is_active": "BOOLEAN DEFAULT 1",
            "is_default": "BOOLEAN DEFAULT 0",
            "supports_text": "BOOLEAN DEFAULT 1",
            "supports_attachments": "BOOLEAN DEFAULT 1",
            "supports_audio": "BOOLEAN DEFAULT 0",
            "supports_documents": "BOOLEAN DEFAULT 0",
            "supports_images": "BOOLEAN DEFAULT 0",
            "created_at": "DATETIME",
            "updated_at": "DATETIME",
        },
        "channel_settings": {
            "value_type": "VARCHAR(50) DEFAULT 'string'",
            "is_secret": "BOOLEAN DEFAULT 0",
            "created_at": "DATETIME",
            "updated_at": "DATETIME",
        },
        "inbound_messages": {
            "channel_id": "INTEGER",
            "source_thread_id": "VARCHAR(255)",
            "direction": "VARCHAR(30) DEFAULT 'inbound'",
            "recipient": "VARCHAR(255)",
            "original_content": "TEXT",
            "raw_payload_json": "TEXT",
            "content_type": "VARCHAR(80)",
            "processing_step": "VARCHAR(80) DEFAULT 'received'",
            "normalized_text": "TEXT",
            "classification_json": "TEXT",
            "extraction_json": "TEXT",
            "customer_id": "INTEGER",
            "order_id": "INTEGER",
            "score": "FLOAT DEFAULT 0",
            "has_audio": "BOOLEAN DEFAULT 0",
            "processing_error": "TEXT",
            "last_processed_at": "DATETIME",
            "created_at": "DATETIME",
            "updated_at": "DATETIME",
        },
        "message_attachments": {
            "ocr_text": "TEXT",
            "transcription_text": "TEXT",
            "is_image": "BOOLEAN DEFAULT 0",
            "is_audio": "BOOLEAN DEFAULT 0",
            "created_at": "DATETIME",
        },
        "normalized_inputs": {
            "metadata_json": "TEXT",
            "created_at": "DATETIME",
        },
        "order_reviews": {
            "reviewer_user_id": "INTEGER",
            "status": "VARCHAR(80) DEFAULT 'pending'",
            "comments": "TEXT",
            "reviewed_at": "DATETIME",
            "created_at": "DATETIME",
        },
        "manual_corrections": {
            "inbound_message_id": "INTEGER",
            "order_id": "INTEGER",
            "order_line_id": "INTEGER",
            "agent_value": "TEXT",
            "corrected_entity_id": "INTEGER",
            "should_learn": "BOOLEAN DEFAULT 0",
            "created_at": "DATETIME",
        },
        "learned_aliases": {
            "source_correction_id": "INTEGER",
            "approved": "BOOLEAN DEFAULT 0",
            "approved_by": "INTEGER",
            "updated_at": "DATETIME",
        },
        "rag_cases": {
            "case_type": "VARCHAR(80)",
            "input_text": "TEXT",
            "agent_initial_result_json": "TEXT",
            "human_corrected_result_json": "TEXT",
            "resolution_summary": "TEXT",
            "linked_customer_id": "INTEGER",
            "embedding_id": "VARCHAR(255)",
            "usefulness_score": "FLOAT DEFAULT 0",
            "approved_for_retrieval": "BOOLEAN DEFAULT 0",
        },
        "scoring_results": {
            "inbound_message_id": "INTEGER",
            "customer_score": "FLOAT DEFAULT 0",
            "product_score": "FLOAT DEFAULT 0",
            "confidence_score": "FLOAT DEFAULT 0",
            "rule_score": "FLOAT DEFAULT 0",
            "block_reason": "TEXT",
            "details_json": "TEXT",
            "created_at": "DATETIME",
        },
        "export_jobs": {
            "file_path": "VARCHAR(500)",
            "remote_path": "VARCHAR(500)",
            "export_format": "VARCHAR(50) DEFAULT 'csv'",
            "destination_type": "VARCHAR(50) DEFAULT 'sftp'",
            "status_message": "TEXT",
            "payload_json": "TEXT",
            "exported_at": "DATETIME",
        },
        "background_jobs": {
            "dedupe_key": "VARCHAR(255)",
            "attempt_count": "INTEGER DEFAULT 0",
            "max_retries": "INTEGER DEFAULT 3",
            "next_retry_at": "DATETIME",
            "last_error_at": "DATETIME",
            "last_error_type": "VARCHAR(120)",
            "last_heartbeat_at": "DATETIME",
        },
        "alerts": {
            "inbound_message_id": "INTEGER",
            "severity": "VARCHAR(50) DEFAULT 'medium'",
            "status": "VARCHAR(50) DEFAULT 'open'",
            "payload_json": "TEXT",
            "resolved_at": "DATETIME",
        },
        "agent_logs": {
            "channel_id": "INTEGER",
            "inbound_message_id": "INTEGER",
            "order_id": "INTEGER",
            "level": "VARCHAR(20) DEFAULT 'info'",
            "event": "VARCHAR(120)",
            "payload_json": "TEXT",
        },
    }
    inspector = inspect(target_engine)
    existing_tables = set(inspector.get_table_names())
    with target_engine.begin() as conn:
        for table, columns in additions.items():
            if table not in existing_tables:
                continue
            existing_columns = {column["name"] for column in inspector.get_columns(table)}
            for column_name, column_type in columns.items():
                if column_name not in existing_columns:
                    conn.execute(text(f"ALTER TABLE {table} ADD COLUMN {column_name} {column_type}"))
